
connections:
- addr: "test_service_1"
  port: 5555
  topic: "test"
  file_extension: "rec"
  sinks:
    - sink_type: "File Sink"
      name: "File_Sink_1"
      flush_time: 5
    - sink_type: "Console Sink"
      name: "Console_Sink_1"
- addr: "test_service_2"
  port: 5556
  topic: "test"
  file_extension: "rec"
  sinks:
    - sink_type: "File Sink"
      name: "File_Sink_2"
    - sink_type: "Console Sink"
      name: "Console_Sink_2"
- addr: "test_service_3"
  port: 5557
  topic: "test"
  file_extension: "rec"
  sinks:
    - sink_type: "Console Sink"
      name: "Console_Sink_3"
    - sink_type: "Compressed Sink"
      name: "Console_Sink_4"
      flush_time: 5
- addr: "test_service_4"
  port: 5558
  topic: "test"
  file_extension: "rec"
  sinks: